### ISSUE TITLE
Don't dump stack when git error occurs

### ISSUE THREAD

**Issue by pfn** [sbt/sbt-git#101]
This is highly annoying when running a git command that fails from the repl.

https://github.com/sbt/sbt-git/blob/master/src/main/scala/com/typesafe/sbt/git/ConsoleGitRunner.scala#L30

Rather than, `error()`, please `throw new MessageOnlyException()` instead.

**Comment by bchazalet** [comment]
I agree it's annoying.

**Comment by bchazalet** [comment]
@dwijnand this was fixed in #104
