### ISSUE TITLE
Defaulting to NOP logger [SLF4J & sbt-git]

### ISSUE THREAD

**Issue by jvican** [sbt/sbt-git#102]
I just installed `sbt-git`. When I execute `sbt`, I get the following message error twice in a row:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation.
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

My version of scala is 2.11.7 and sbt is 0.13.9, running on a Gentoo Linux.

**Comment by ssemichev** [comment]
I have the same warnings

Scala 2.10, sbt 0.13.8 and 0.13.9

**Comment by bchazalet** [comment]
we all do. Are you complaining about the warning being printed or worried that it might have consequences?

**Comment by jvican** [comment]
@bchazalet: both, it's quite disturbing and it may have consequences.

**Comment by nscarcella** [comment]
+1 the warning is quite bothersome, specially if using JGIT.

**Comment by dwijnand** [comment]
Duplicate of #69, see sbt/sbt#1931.
