### ISSUE TITLE
GitVersioning and git submodules

### ISSUE THREAD

**Issue by irundaia** [sbt/sbt-git#103]
Hi, 

I'm using `GitVersioning` to determine the version of my sbt project. I'm having a problem with a submodule though. I'm using a tagged commit (on the master branch) from a different git repository. Since the release, new commit have been added to the master branch. 

Now, git reports that my working directory is clean (for both my main repo and the submodule's repo). However, due to the fact that submodule's in a detached HEAD state the version of my project is appended with `-SNAPSHOT`.

Any idea on how I could solve this (short of overriding the version manually)?

**Comment by bchazalet** [comment]
if you're only annoyed by the -SNAPSHOT, you can suppress that suffix by overriding `uncommittedSignifier `, e.g in your build.sbt:
```
uncommittedSignifier := None
```

**Comment by bchazalet** [comment]
Otherwise, I think we having multiple issues with projects containing git submodules (like #97). I don't think anyone really thought carefully about those kind of projects, and it's time that we do.

**Comment by irundaia** [comment]
Well, the point is, when I try to publish the project, bintray won't accept it since it only accept numeric versions. 

Thanks for the workaround though.
