### ISSUE TITLE
plugin settings are not tab completed in console

### ISSUE THREAD

**Issue by blbradley** [sbt/sbt-git#106]
It works for [sbt-docker](https://github.com/marcuslonnberg/sbt-docker) but not this plugin. But I can inspect plugin keys.

Example:

```
> show dock
::                   docker               dockerBuildAndPush   dockerPush           dockerTags
> show git
{invalid input}
> show gitCurrentBranch
[info] master
```

The first two commands were tab completed after the second word.

 `dockerTags` key is my own.

**Comment by dwijnand** [comment]
I think this is due to an sbt bug: build-level settings didn't tab-complete.

We fixed this so you should find in modern sbt versions it works.
