### ISSUE TITLE
gitUncommittedChanges say true when `git status` says I don't have changes

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-git#109]
## steps
1. I tag my commit to v0.1.0-M3.
2. Use git versioning.
3. `git status` says I don't have any uncommitted changes.

I'm not sure if you can reproduce it, but I am seeing it now trying to release sbt/incrementalcompiler 0.1.0-M3.
## problem
1. `version` is `0.1.0-M3-SNAPSHOT`
2. `gitUncommittedChanges` returns `true`
## expectation
1. `version` is `0.1.0-M3`
2. `gitUncommittedChanges` returns `false`
## notes

Maybe if there's a task that displays my uncommitted changes it would help.

**Comment by bchazalet** [comment]
@eed3si9n I think you may be running into #92 like many others. Usually it has to do with symlinks or some character case issue on mac os x.

We don't have a solution for this, although I am hoping that upgrading sbt-git to the latest JGit will fix it.

On last resort, you could disable the SNASHOT suffix like this:
```
git.uncommittedSignifier := None
```

**Comment by eed3si9n** [comment]
Probably. I'm seeing this on Mac OS X as well.

**Comment by danielnegri** [comment]
+1

**Comment by mikedmcfarland** [comment]
Having the same problem, even publishing the jgit4.2 branch I was still seeing it on OSX (only when I use symlinks in my repo). Decided to use git directly for that one setting:
```
git.gitUncommittedChanges := {
  Process("git status --porcelain").lines.length > 0
}
```
so far so good. I'd actually like a ReadableGit interface that was just using the git CLI. Having it be in pure java is not a feature for me personally, and the fact that the results differ at all is troubling. If I find the time I might create one and send a PR.

**Comment by dwijnand** [comment]
Upgraded to JGit 4.5 in #99 which should fix this.

**Comment by japgolly** [comment]
I'm hitting this now. Would somebody mind publishing a new release, please?
