### ISSUE TITLE
No branch prompt if used with play framework projects

### ISSUE THREAD

**Issue by jan0sch** [sbt/sbt-git#111]
Hi,

I just noticed that the `.enablePlugins(GitBranchPrompt)` setting has no effect if used in a play framework project. As long as `.enablePlugins(PlayScala)` is in the `build.sbt` there is no branch prompt. :-(

**Comment by nlochschmidt** [comment]
As a workaround, It's still possible to overwrite the PlayScala prompt explicitly: 

`shellPrompt := GitCommand.prompt`
