### ISSUE TITLE
Extracting scmInfo directly from git

### ISSUE THREAD

**Issue by nscarcella** [sbt/sbt-git#113]
Hi guys!

I needed the scmInfo field initialized with the repo information so I could deploy to Sonatype. Writing this info manually in each project started to become a bit of a bother, so I tried to make a generic implementation that I could use everywhere.

I ended up writing something like this:

``` scala
scmInfo := {
  val remote = """origin[ \t]+git@([^:]*):(.*)\.git[ \t]+\(fetch\)""".r
  Process("git remote -v").lines_!.collect {
    case remote(domain, repo) =>
      ScmInfo(
        url(s"https://$domain/$repo"),
        s"scm:git:https://$domain/$repo.git",
        Some(s"scm:git:git@$domain:$repo.git")
      )
  }.headOption
}
```

With this addition the scmInfo gets automatically set to the project's origin remote (or left blank if it doesn't exist).

I was about to add this in all my projects but then I thought that scmInfo initialization may be a nice thing for the git plugin to provide directly, since it is a standard and quite common sbt key. Of course I understand each project may prefer to specify this at will, but it seems like a fair default to me (and it would save me some time :P).

Then again, perhaps you are not providing the initialization of scmInfo intentionally for some reason, or maybe it is not as common as I though to set it to the origin...

Anyway, I was wondering if you like the idea of adding this (or some other kind of default initialization for the scmInfo key) to your plugin. If so, I can make a PR if you want me to.

Let me know what you think.

**Comment by dwijnand** [comment]
Send a PR. Sounds reasonable to me.

**Comment by jvican** [comment]
This should be closed since https://github.com/sbt/sbt-git/pull/117 was merged.
