### ISSUE TITLE
Release with fix for issue #92

### ISSUE THREAD

**Issue by neingeist** [sbt/sbt-git#119]
I've seen issue #92 (JGit erroneously reports uncommited changes) in one of my projects. Could you please release a new version of sbt-git that includes the fix?

**Comment by ghl3** [comment]
There are also a number of other nice things in master that aren't yet in a release (for example, `git. gitHeadCommitDate`).  Would be great to get those into a release as well.

**Comment by leonardehrenfried** [comment]
Yes, I'd really like to see a release, too.

**Comment by dwijnand** [comment]
https://github.com/sbt/sbt-git/releases/tag/v0.9.0

**Comment by neingeist** [comment]
Thanks! :)
