### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt-git#120]
The last release is from 2015 with jGit version 3.7.0. There haven't been a lot of commits and PRs are pending.

**Comment by bchazalet** [comment]
Some us are still here (coming up with these PRs) but we don't have admin rights. @dwijnand did some merging for us not too long ago, but the release process has been stale for a long while now.

**Comment by hseeberger** [comment]
I'd like to continue using sbt-git, in particular because I have other plugins that depend on jGit and I don't want to head straight into dependency hell.

@jsuereth, @dwijnand are you still actively maintaining this? If not, would you mind if others take over?

**Comment by dwijnand** [comment]
Hey. Boris is right, I started taking care of maintaining this plugin. Then I mass-unsubscribed in December so this dropped off my radar. I'm happy to share maintainership. I've invited you @hseeberger. @bchazalet were you interested too? I'll try and get a release out today.

**Comment by bchazalet** [comment]
@dwijnand yes, I'd be happy to help with the maintenance.

**Comment by dwijnand** [comment]
Btw, there's also a Gitter room where we can chat: https://gitter.im/sbt/sbt-git
