### ISSUE TITLE
Different behavior on Jenkins than locally

### ISSUE THREAD

**Issue by mirosval** [sbt/sbt-git#123]
I have the following sbt-git config:

```scala
git.useGitDescribe := true
git.formattedShaVersion := { (git.gitHeadCommit in ThisBuild).value.map(_.substring(0, 6)) }
git.gitTagToVersionNumber := { tag: String =>
  if (tag matches "v[0-9]+\\..*") {
    Some(s"${tag.drop(1)}-${git.gitCurrentBranch.value}")
  } else {
    None
  }
}
```

On my local machine `sbt version` produces `0.1.0-22-g482c929-master`, but on Jenkins the same code produces `my_package_2.11-0.1.0-22-g482c929-482c929de3ca0d1a7fbbd83c50c549c020ba3969-javadoc.jar`. Any idea what is going on?

**Comment by bchazalet** [comment]
how is your tag named? Is it possible you are, somehow, in a detached state on jenkins?

**Comment by mirosval** [comment]
I think that's entirely possible, because the Jenkins Git plugin does:

```
00:00:00.135  > /usr/bin/git fetch --tags --progress git@repo.git +refs/heads/*:refs/remotes/origin/*
00:00:00.701  > /usr/bin/git rev-parse refs/remotes/origin/master^{commit} # timeout=10
00:00:00.707  > /usr/bin/git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
00:00:00.718 Checking out Revision 482c929de3ca0d1a7fbbd83c50c549c020ba3969 (refs/remotes/origin/master)
00:00:00.722  > /usr/bin/git config core.sparsecheckout # timeout=10
00:00:00.724  > /usr/bin/git checkout -f 482c929de3ca0d1a7fbbd83c50c549c020ba3969
00:00:00.745  > /usr/bin/git rev-list 869b98d9393e1faa3924cea3b83d2240c3054e3e # timeout=10
```

I guess `git checkout -f <sha>` leaves us in the detached head state.

Then the question is why does the detached head state not hit the same code path as non-detached. In terms of commits it should be the same no? The only difference is that the HEAD ref is not pointing to the currently checked out commit.

**Comment by bchazalet** [comment]
well, your two versions are not so different (I'm ignoring the my_package prefix and javadoc suffix as they most probably come from the package name rather than the version):
`0.1.0-22-g482c929-master`
versus
`0.1.0-22-g482c929-482c929de3ca0d1a7fbbd83c50c549c020ba3969`

If we assume that you are in a detached state, then there is no branch name per se, and git (or JGit) my just choose the HEAD sha as the closest thing (technically a branch is just a pointer to a commit). Does that make sense?

**Comment by mirosval** [comment]
Ah I understand, so the commit hash is there instead of the branch name. Thank you!
