### ISSUE TITLE
Release for 1.0.0-M5

### ISSUE THREAD

**Issue by ScalaWilliam** [sbt/sbt-git#125]
Notes are here:
http://developer.lightbend.com/blog/2017-04-18-sbt-1-0-roadmap-and-beta1/#cross-building-sbt-1-0-plugin-from-sbt-0-13

**Comment by bchazalet** [comment]
Indeed, it'd be good to get on that train.

**Comment by leonardehrenfried** [comment]
Appears to be addressed in #127 however, the change seems quite small.

Is that enough to cross-compile for sbt 1.0.0?

**Comment by dwijnand** [comment]
Yes, indeed it is enough.
