### ISSUE TITLE
scmInfo not discovered when `.git` is missing from the git origin

### ISSUE THREAD

**Issue by raboof** [sbt/sbt-git#157]
When the origin is `git@github.com:akka/akka` rather than `git@github.com:akka/akka.git` it appears it is not picked up and it doesn't contribute the `scmInfo` section to the pom.

(sorry if this is a bit terse, haven't tested in depth but wanted to file this issue before I forget ;) )

**Comment by anilkumarmyla** [comment]
Ran into this today, early awaiting a release with this fix

**Comment by SethTisue** [comment]
@anilkumarmyla see #182, #184, #185

**Comment by raboof** [comment]
@anilkumarmyla 1.0.1 has it!
