### ISSUE TITLE
Disable JGit?

### ISSUE THREAD

**Issue by ghost** [sbt/sbt-git#160]
The README states we need [enable JGit explicitly](https://github.com/sbt/sbt-git#using-jgit) via `useJGit`, but apparently (see eg #110) this plugin uses JGit regardless.

Is there a way to disable JGit in favour of the native Git executable?

**Comment by stewSquared** [comment]
@swiesner-dlr It's been a year. Did you find a workaround?

**Comment by swiesner-dlr** [comment]
I stopped using worktrees, I guess :)

**Comment by mkurz** [comment]
I think this issue can be closed now that
- #168

got merged.
