### ISSUE TITLE
sbt community repo

### ISSUE THREAD

**Issue by babsher** [sbt/sbt-git#180]
Will this plugin be migrated the SBT community repo? sbt git is currently unavailable for download because of the bintray brownout today.

https://github.com/sbt/sbt/issues/6294

**Comment by SethTisue** [comment]
literally everything in https://repo.scala-sbt.org is being migrated.

**Comment by SethTisue** [comment]
@dwijnand can I have write rights in this repo, so I can close this ticket?

**Comment by babsher** [comment]
Closing because the plugin will be migrated
