### ISSUE TITLE
Move to com.github.sbt?

### ISSUE THREAD

**Issue by mkurz** [sbt/sbt-git#198]
I am a bit wondering why you (still) use `com.typesafe.sbt` and didn't move to `com.github.sbt`?
It seems you are the only one still publishing under this id: https://repo1.maven.org/maven2/com/typesafe/sbt/
As far as I understand, now that https://repo.scala-sbt.org/ is read only, sbt-plugins hosted under the [sbt Github organisation](https://github.com/sbt), started moving to `com.github.sbt` (https://repo1.maven.org/maven2/com/github/sbt/)

**Comment by raboof** [comment]
I think the reason is mostly just that nobody did it yet ;)

**Comment by mkurz** [comment]
That's a good point :wink: So this confirms my assumption that `com.github.sbt` is the place to be for sbt plugins and `com.typesafe.sbt` is deprecated. Thanks!

**Comment by raboof** [comment]
Don't take my word as authoritative, I haven't followed it closely, but it seems reasonable to me to follow https://github.com/sbt/sbt-unidoc/pull/95/files#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R3 and https://github.com/sbt/sbt-ci-release/pull/210/files

**Comment by mkurz** [comment]
Just a reminder: When moving to `com.github.sbt` don't forget to tell scala-steward about it, as an example: https://github.com/scala-steward-org/scala-steward/pull/2488

**Comment by mkurz** [comment]
@SethTisue Voilà -> #205

**Comment by mkurz** [comment]
@SethTisue Are the sonatype credentials for this repo are set up?

**Comment by SethTisue** [comment]
(i'll respond on the PR)
