### ISSUE TITLE
Git versioning with tags

### ISSUE THREAD

**Issue by schmmd** [sbt/sbt-git#27]
I am trying to understand the rules used by sbt-git to build a version.  If I make a tag at the present commit "v5.0.0" then `sbt version` shows the version to be `5.0.0`.  If I then make a new commit, `sbt version` shows the version to be `1.0-77c7b821e9450c17c9e1c43861cbca3e5feddd46`.  Shouldn't it be `5.0.0-77c7b821e9450c17c9e1c43861cbca3e5feddd46`?  Where is the `1.0` coming from?

**Comment by jsuereth** [comment]
git describe is now working and tested.
