### ISSUE TITLE
duplicated output

### ISSUE THREAD

**Issue by Morgothdev** [sbt/sbt-git#34]
It's duplicated output from git:

I've ~/.sbt/0.13/plugins/plugins.sbt
resolvers ++= Seq(
	"Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/",
	"jgit-repo" at "http://download.eclipse.org/jgit/maven")
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "2.4.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.6.2")

ant output from example git command:

$ sbt
Loading /usr/share/sbt/bin/sbt-launch-lib.bash
[info] Loading global plugins from /home/mateusz/.sbt/0.13/plugins
[info] Loading project definition from /home/mateusz/workspaces/scala-workspaces/moje_projekciki/PDFGen/project
[info] Set current project to hello (in build file:/home/mateusz/workspaces/scala-workspaces/moje_projekciki/PDFGen/)
> git
> [info] usage: git [--version] [--help] [-C <path>] [-c name=value]
[info]            [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
[info]            [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
[info]            [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
[info]            <command> [<args>]
[info] 
[info] The most commonly used git commands are:
[info]    add        Add file contents to the index
[info]    bisect     Find by binary search the change that introduced a bug
[info]    branch     List, create, or delete branches
[info]    checkout   Checkout a branch or paths to the working tree
[info]    clone      Clone a repository into a new directory
[info]    commit     Record changes to the repository
[info]    diff       Show changes between commits, commit and working tree, etc
[info]    fetch      Download objects and refs from another repository
[info]    grep       Print lines matching a pattern
[info]    init       Create an empty Git repository or reinitialize an existing one
[info]    log        Show commit logs
[info]    merge      Join two or more development histories together
[info]    mv         Move or rename a file, a directory, or a symlink
[info]    pull       Fetch from and integrate with another repository or a local branch
[info]    push       Update remote refs along with associated objects
[info]    rebase     Forward-port local commits to the updated upstream head
[info]    reset      Reset current HEAD to the specified state
[info]    rm         Remove files from the working tree and from the index
[info]    show       Show various types of objects
[info]    status     Show the working tree status
[info]    tag        Create, list, delete or verify a tag object signed with GPG
[info] 
[info] 'git help -a' and 'git help -g' lists available subcommands and some
[info] concept guides. See 'git help <command>' or 'git help <concept>'
[info] to read about a specific subcommand or concept.
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
The most commonly used git commands are:
   add        Add file contents to the index
   bisect     Find by binary search the change that introduced a bug
   branch     List, create, or delete branches
   checkout   Checkout a branch or paths to the working tree
   clone      Clone a repository into a new directory
   commit     Record changes to the repository
   diff       Show changes between commits, commit and working tree, etc
   fetch      Download objects and refs from another repository
   grep       Print lines matching a pattern
   init       Create an empty Git repository or reinitialize an existing one
   log        Show commit logs
   merge      Join two or more development histories together
   mv         Move or rename a file, a directory, or a symlink
   pull       Fetch from and integrate with another repository or a local branch
   push       Update remote refs along with associated objects
   rebase     Forward-port local commits to the updated upstream head
   reset      Reset current HEAD to the specified state
   rm         Remove files from the working tree and from the index
   show       Show various types of objects
   status     Show the working tree status
   tag        Create, list, delete or verify a tag object signed with GPG
'git help -a' and 'git help -g' lists available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
>

**Comment by jsuereth** [comment]
Should be fixed in 0.8
