### ISSUE TITLE
Make git.baseVersion optional?

### ISSUE THREAD

**Issue by GitsMcGee** [sbt/sbt-git#41]
Hello,

At my company, we are running continuous deployment, and as such, deploy on each commit. Since this is the case, we use the git commit SHA as the actual version itself. This plugin is perfect for that, but it prepends a 1.0- to the git commit sha. You can override it by specifying `git.baseVersion := "XYZ"`, but it's impossible to have nothing at all. 

Obviously I'm being finicky here, but it's driving my OCD brain crazy! It would be great if there was a way to exclude the base version.

**Comment by jsuereth** [comment]
Fixed in 0.7.1
