### ISSUE TITLE
version

### ISSUE THREAD

**Issue by bchazalet** [sbt/sbt-git#45]
The versionning with git does not work if sbt base directory does not contain the .git directory. 

I have a repo with the following folders:
```
my-project
|-- code
       |-- build.sbt
       |-- src
|-- .git
```
See the results of the following commands:
```
[bloomberg-update-service] $ show version
[info] 1.0.3-20140812T140719

[bloomberg-update-service] $ show gitCurrentBranch
[info]

[bloomberg-update-service] $ show gitHeadCommit
[info] None
```

Note that git console works even if I force the use of JGit, i.e. JGit can find that the .git folder is one folder up.
```
[bloomberg-update-service] $  set useJGit
[bloomberg-update-service] $ git status
[info] # On branch master
...
```

**Comment by jsuereth** [comment]
Should be fixed in 0.7 release
