### ISSUE TITLE
Migrate to use auto-plugin feature

### ISSUE THREAD

**Issue by jaceklaskowski** [sbt/sbt-git#50]
I'd love getting rid of the `build.sbt` configuration step whatsoever by migrating the plugin to use auto-plugin feature available since sbt 0.13.5.

Quoting [the official documentation of sbt](http://www.scala-sbt.org/0.13/docs/Plugins.html):

> sbt 0.13.5 intoduces auto plugin with improved dependency management among the plugins and explicitly scoped auto importing. Going forward, our recommendation is to migrate to the auto plugins.

The last sentence makes the migration highly welcome.

**Comment by jsuereth** [comment]
Yes, woudl love to migrate this soon!

**Comment by hseeberger** [comment]
+1

**Comment by jsuereth** [comment]
0.8.0 is released.

**Comment by hseeberger** [comment]
Awesome! Thanks, @jsuereth. Safe travels!
