### ISSUE TITLE
Default version-property override should not be 'project.version'

### ISSUE THREAD

**Issue by agilestevesmith** [sbt/sbt-git#64]
The default version-property override should not be 'project.version', as many build systems provide that property out of the box and out of the control of the user.

If you do not specify your own override in your project sbt file you can end up in a nasty situation where sbt-git insists on version-property='project.version' overriding all other versioning strategies, and your build system insisting on providing project.version=48 etc.

I suggest version-property should be an Option. It's an override so by definition it's optional. If it is not specified, the override strategy should be ignored entirely.

@jakobgrunig
@charleskubicek

**Comment by jsuereth** [comment]
i think the person who submitted that WANTED it to be project.version.  I'm ok migrating to something different (and documenting it).   Would you like to submit a patch?
