### ISSUE TITLE
JGit depends on SLF4J

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt-git#69]
Warnings are printed:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Should we write a SLF4J backend for sbt?

**Comment by jsuereth** [comment]
Can you open a ticket to sbt about this?  

Yes, it should have an slf4j backend.  Too many plugins depend on it, and if we do something in sbt-git, we may break other plugins.

**Comment by hseeberger** [comment]
Closing, because ticket against sbt created here: https://github.com/sbt/sbt/issues/1931

**Comment by matthieu-labas** [comment]
Is there any plan to remove SLF4J dependency from JGIT? I understand from the other ticket that it's part of the core API, but it feels cumbersome to have to download yet-another-logging-framework each time we want to use a new library...

**Comment by nscarcella** [comment]
Sorry for resurrect this, but Is there any workaround to stop seeing this warnings until the SBT fix is ready? I have sbt-git on my global and nothing I do seems to get rid of this. I've tried adding slf4j-nop.jar to my projects /lib and even to the ~/.sbt/0.13/plugins/lib/ folder and still get the error.

I'm not even using JGit...

**Comment by hseeberger** [comment]
@nscarcella, add `libraryDependencies += "org.slf4j" % "slf4j-nop" % "1.7.21"` to `.sbt/0.13/plugins/plugins.sbt`
