### ISSUE TITLE
Trying to set version from git tag

### ISSUE THREAD

**Issue by mjcramer** [sbt/sbt-git#71]
I am trying to set the project version from git using sbt-git and my settings are as follows...

lazy val special = project.in(file("."))
  .settings(commonSettings: _*)
  .enablePlugins(GitVersioning, GitBranchPrompt)
  .settings(
    git.gitTagToVersionNumber := { tag: String =>
      Some("special_tag")
    }
  )

The output of 'git tag' is 'v0.9.9' so you would think that my version would be set to "special_tag" but it's not, it gets set to the last SHA1 postpended with "SNAPSHOT".  It's as if sbt-git is not paying attention to the existing tags at all. I can verify this by running 'sbt -jvm-debug' and setting a breakpoint at line 118 in SbtGit.scala:

118:  gitCurrentTags := gitReader.value.withGit(_.currentTags),

If I put a watch on gitReader.value and step into this function, I can clearly see a "not implemented" exception being thrown. Is this a known issue? The documentation on the readme seems to imply that this is supposed to work. Any insight?

**Comment by bchazalet** [comment]
It works for me with the following build.sbt

```
lazy val special = project.in(file("."))
.enablePlugins(GitVersioning, GitBranchPrompt)
.settings(
  git.gitTagToVersionNumber := { tag: String =>
    Some("special_tag")
  }
)
```
Then I get:
```
special(master)> git tag
[info] v0.1
special(master)> show version
[info] special_tag
```

Are you using windows? What version of sbt and sbt-git are you pointing to?
And have you reloaded sbt after the tag was created?

**Comment by mjcramer** [comment]
Okay, I think I see the problem. I was not originally forthcoming with the entire scope of the issue apparently. My original project is a multi-module project in which I share settings across multiple modules. I tried to simplify the example but I should have done a more exhaustive test. When I created a simple single project with a git tag, it worked as you have pointed out. If it add submodules as additional projects, it will continue to work UNLESS I 'enablePlugins' in one of the submodules, which causes it to reset my git-related settings under the context of that submodule. My original project uses shared settings and that was the root of my problem. Ultimately my ignorance of how sbt loads plugins proliferated this misconception. I should have reconstructed the issue from scratch for submitting it and I would have realized the mistake. Thank you for responding to this issue, and I'm sorry for wasting your time!

**Comment by bchazalet** [comment]
No problem, glad you've solved your issue!

**Comment by mjcramer** [comment]
Seems I spoke too soon. I tried out this project: git@github.com:mjcramer/sbt-git-test.git

and here's the output:

~/projects/data/sbt-git-test] (master^) sbt
[info] Loading global plugins from /Users/michael.cramer/.sbt/0.13/plugins
[info] Loading project definition from /Users/michael.cramer/projects/data/sbt-git-test/project
[info] Updating {file:/Users/michael.cramer/projects/data/sbt-git-test/project/}sbt-git-test-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to special (in build file:/Users/michael.cramer/projects/data/sbt-git-test/)
special(master)> show version
[info] 95322edc77ad4127956bd2b9ca6bfb4ceb3afbba
special(master)> git tag
[info] v1.0
special(master)> git branch
[info] * master
special(master)> exit

**Comment by mjcramer** [comment]
Now it's back to just printing the sha hash while ignoring my git tag...

**Comment by mjcramer** [comment]
The behavior came back shortly after I added a "develop" branch to my other project. Now I cannot get it to work at all, even after rolling back all my changes. I dunno if that has anything to do with it, but I'm just throwing it out there...

**Comment by bchazalet** [comment]
You're problem is that there is no tag associated with HEAD.

Your v1.0 tag points at some other commit:
```
special(master)> git show v1.0
[info] commit d76e631bfd524849266f25dcd328883e83be0af4
[info] Author: Michael Cramer <michael.cramer@creditkarma.com>
[info] Date:   Tue Apr 7 09:27:04 2015 -0700
[info]
[info]     init
[info]
```

You can see the tags associated with HEAD commit in sbt:
```
special(master)> show git-current-tags
[info] List()
```

if you create a new tag pointing at HEAD, everything comes back into order:
```
special(master)> git tag v2.0
special(master)> reload
special(master)> show git-current-tags
[info] List(v2.0)
special(master)> show version
[info] v2.0-special
```

**Comment by mjcramer** [comment]
Ahhhhhh!!! Thanks so much!
