### ISSUE TITLE
Support setting isSnapshot

### ISSUE THREAD

**Issue by jroper** [sbt/sbt-git#79]
If there is no current tag for the build, then sbt-git should set isSnapshot to true, or at least provide an option to do that, so that builds that publish nightlies to a snapshot repository still work.

**Comment by jsuereth** [comment]
yes, it should

**Comment by thunderc90** [comment]
Not sure this should've been closed..

Here's what I'm thinking:
80 appeared to be about no tags existing in the repo, whereas this one appears to be describing when no tag is attributed to the current head commit. 

I'm imagining a workflow like this for example:
1. git tag v0.1.0
2. git.baseversion set to 0.2.0 and committed

then repeat those two steps for releases. Ideally after the commit for step 2 is done, I'd like sbt version to return '0.2.0-gitcommittishhere-SNAPSHOT', but currently I get '0.2.0-gitcommittishhere'.
