### ISSUE TITLE
Docs Say 0.8.3 But Latest on Bintray is 0.8.0

### ISSUE THREAD

**Issue by jamesward** [sbt/sbt-git#84]
https://github.com/sbt/sbt-git#installation
http://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbt/sbt-git/scala_2.10/sbt_0.13/

**Comment by metasim** [comment]
@jsuereth Is this a docs error, or a publishing error?

**Comment by jsuereth** [comment]
publishing error, should be fixed now.
