### ISSUE TITLE
Build using sbt-git fails non-deterministically on TravisCI

### ISSUE THREAD

**Issue by djspiewak** [sbt/sbt-git#85]
Example: https://travis-ci.org/scalaz/scalaz-stream/jobs/60127015

Any idea how I can convince sbt-git that Git *is* in fact installed on Travis?  JGit basically doesn't work.

**Comment by bchazalet** [comment]
The current implementation of sbt-git always uses JGit for things that are not coming from the user input/commands and there is no setting or detection that can alter that (again, in the current implementation):
https://github.com/sbt/sbt-git/blob/master/src/main/scala/com/typesafe/sbt/git/ReadableGit.scala#L31
and 
https://github.com/sbt/sbt-git/blob/527448468f2451402322a7e1ba4961718dc1d499/src/main/scala/com/typesafe/sbt/SbtGit.scala#L116

so, my opinion is that you can't. Does the error always happen in com.typesafe.sbt.git.JGit.hasUncommittedChanges?

**Comment by djspiewak** [comment]
@bchazalet It looks like it can also happen in `com.typesafe.sbt.git.JGit.currentTags`.

Can we just have sbt-git bypass its JGit logic in the case where `project.version` is defined?  I just want the ability to turn it off for TravisCI, so I don't mind losing functionality (i.e. real versions) in that environment in the process.

**Comment by bchazalet** [comment]
or maybe we can use JGit safely, see PR.

**Comment by jsuereth** [comment]
This should be fixed in 0.8.4.

Thanks @bchazalet for the fix!
