### ISSUE TITLE
if no git tags, can't load project with `useGitDescribe := true`

### ISSUE THREAD

**Issue by refried** [sbt/sbt-git#89]
Would it be ok to have a fallback `version`, like when `useGitDescribe := false`?

**Comment by jsuereth** [comment]
Yes.  PR welcome.

**Comment by 2m** [comment]
Hey, @fernandomora are you planning to provide a PR to fix this issue? :)

**Comment by fernandomora** [comment]
@2m As I know this bug was fixed and merged in PR #88 and later refactored and merged in PR #94, but it still han't been released

**Comment by 2m** [comment]
Great! Then this issue should be closed. Looking forward to the release then.

**Comment by 2m** [comment]
What can I do to help releasing new version of sbt-git with this fix? This bug really bites new projects when there are no tags yet in the repository.

**Comment by jsuereth** [comment]
@2m If you'd like to cut a release, it should be as easy as tagging a version and pushing to bintray.  Do you need credentials to do so? I can give these to you.

**Comment by 2m** [comment]
I think I am fine with bintray credentials. But I can not manage github project like closing fixed issues, etc.
