### ISSUE TITLE
Upgrade to jgit 4

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt-git#98]

**Comment by bchazalet** [comment]
Note that JGit 4 requires java 7, which is fine by me but might need a note in the readme.

https://wiki.eclipse.org/JGit/New_and_Noteworthy/4.0

**Comment by jsuereth** [comment]
yeah, I'd be ok doing this with a few additoinal fixes and a bump to 1.0

**Comment by hseeberger** [comment]
1.0 sounds fantastic!

**Comment by dwijnand** [comment]
Done in #99
